id: I87432D76
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T00:33:51+00:00'
last_modified: '2022-06-09T08:00:50.365335+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20563
  title: སྙན་རྩོམ་གཅེས་བཏུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    8DAD:
      image_group_id: I4689
      title: ''
      total_pages: 532
      order: 1
      base_file: 8DAD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
