id: P007959
initial_creation_type: ocr
source_metadata:
  id: bdr:W20563
  title: སྙན་རྩོམ་གཅེས་བཏུས
  author: ''
  volumes:
    bb8863f912294b5ba16752ce7c0674d3:
      image_group_id: I4689
      title: ''
      volume_number: 1
      total_pages: 532
      base_file: v001.txt
ebook_metadata:
  title: སྙན་རྩོམ་གཅེས་བཏུས
  author: ''
  sku: P007959
  cover: cover.jpg
  layers:
  - pagination
